#!/bin/bash

time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_c_hihi res/sol0.txt > res/A.u_c_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_c_hilo res/sol1.txt > res/A.u_c_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_c_lohi res/sol2.txt > res/A.u_c_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_c_lolo res/sol3.txt > res/A.u_c_lolo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_i_hihi res/sol4.txt > res/A.u_i_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_i_hilo res/sol5.txt > res/A.u_i_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_i_lohi res/sol6.txt > res/A.u_i_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_i_lolo res/sol7.txt > res/A.u_i_lolo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_s_hihi res/sol8.txt > res/A.u_s_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_s_hilo res/sol9.txt > res/A.u_s_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_s_lohi res/sol10.txt > res/A.u_s_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_s_lolo res/sol11.txt > res/A.u_s_lolo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_c_hihi res/sol12.txt > res/B.u_c_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_c_hilo res/sol13.txt > res/B.u_c_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_c_lohi res/sol14.txt > res/B.u_c_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_c_lolo res/sol15.txt > res/B.u_c_lolo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_i_hihi res/sol16.txt > res/B.u_i_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_i_hilo res/sol17.txt > res/B.u_i_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_i_lohi res/sol18.txt > res/B.u_i_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_i_lolo res/sol19.txt > res/B.u_i_lolo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_s_hihi res/sol20.txt > res/B.u_s_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_s_hilo res/sol21.txt > res/B.u_s_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_s_lohi res/sol22.txt > res/B.u_s_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_s_lolo res/sol23.txt > res/B.u_s_lolo_SEQ.log)

