#!/bin/bash

time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_c_hihi seq/sol0.txt > seq/A.u_c_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_c_hilo seq/sol1.txt > seq/A.u_c_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_c_lohi seq/sol2.txt > seq/A.u_c_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_c_lolo seq/sol3.txt > seq/A.u_c_lolo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_i_hihi seq/sol4.txt > seq/A.u_i_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_i_hilo seq/sol5.txt > seq/A.u_i_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_i_lohi seq/sol6.txt > seq/A.u_i_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_i_lolo seq/sol7.txt > seq/A.u_i_lolo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_s_hihi seq/sol8.txt > seq/A.u_s_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_s_hilo seq/sol9.txt > seq/A.u_s_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_s_lohi seq/sol10.txt > seq/A.u_s_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/A.u_s_lolo seq/sol11.txt > seq/A.u_s_lolo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_c_hihi seq/sol12.txt > seq/B.u_c_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_c_hilo seq/sol13.txt > seq/B.u_c_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_c_lohi seq/sol14.txt > seq/B.u_c_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_c_lolo seq/sol15.txt > seq/B.u_c_lolo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_i_hihi seq/sol16.txt > seq/B.u_i_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_i_hilo seq/sol17.txt > seq/B.u_i_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_i_lohi seq/sol18.txt > seq/B.u_i_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_i_lolo seq/sol19.txt > seq/B.u_i_lolo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_s_hihi seq/sol20.txt > seq/B.u_s_hihi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_s_hilo seq/sol21.txt > seq/B.u_s_hilo_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_s_lohi seq/sol22.txt > seq/B.u_s_lohi_SEQ.log)
time(./MainSeq CHC_SEQ.cfg ../../ProblemInstances/HCSP/1024x32.mod/B.u_s_lolo seq/sol23.txt > seq/B.u_s_lolo_SEQ.log)

